# Generated by Django 3.1.2 on 2020-10-18 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('branch_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='center',
            fields=[
                ('center_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=30)),
                ('center_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='collection_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_day', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='collection_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GLA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cot_balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('param_interest_rate_gl', models.IntegerField()),
                ('param_interest_rate_glp', models.IntegerField()),
                ('param_interest_rate_glg', models.IntegerField()),
                ('param_lpf_rate', models.IntegerField()),
                ('param_share_purchase_rate', models.IntegerField()),
                ('param_base_share_value', models.IntegerField()),
                ('param_gold_appraisal_rate', models.IntegerField()),
                ('param_gold_rate_gl', models.IntegerField()),
                ('param_gold_rate_glp', models.IntegerField()),
                ('param_gold_rate_glg', models.IntegerField()),
                ('param_cot_repay_rate_recommended', models.IntegerField()),
                ('req_gold_loan_amount', models.IntegerField()),
                ('req_netweight_gold', models.BooleanField()),
                ('tr_lead_entered', models.DateField()),
                ('tr_request_taken', models.DateField()),
                ('tr_gla_cancelled', models.DateField()),
                ('retrieval_loan_amount_requested', models.IntegerField()),
                ('tr_retrieval_loan_requested', models.DateField()),
                ('tr_retrieval_completed', models.DateField()),
                ('reason_for_cancellation', models.TextField()),
                ('disbursement_schedule', models.DateField()),
                ('tr_disbursement', models.DateField()),
                ('gl_gold_net_weight', models.IntegerField()),
                ('gl_loan_amount', models.IntegerField()),
                ('gl_tenure', models.IntegerField()),
                ('gl_interest_rate', models.IntegerField()),
                ('gl_date_of_first_installment', models.DateField()),
                ('gl_lpf', models.IntegerField()),
                ('gl_share_purchase', models.IntegerField()),
                ('gl_gold_appraisal_fee', models.IntegerField()),
                ('gl_cot_repayment', models.IntegerField()),
                ('gl_total_retrieval_amount', models.IntegerField()),
                ('gla_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('group_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=30)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_app.center')),
                ('collection_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_app.collection_time')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('mem_num', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('middle_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('aadhar', models.CharField(max_length=30, null=True)),
                ('pan', models.CharField(max_length=30, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('mobile_registred', models.CharField(max_length=10, null=True)),
                ('mobile_whatsapp', models.CharField(max_length=10, null=True)),
                ('date_of_signup', models.DateField(null=True)),
                ('date_of_memstart', models.DateField(null=True)),
                ('cot_balance', models.IntegerField(null=True)),
                ('cot_emi', models.IntegerField(null=True)),
                ('sa_balance', models.IntegerField(null=True)),
                ('date_of_food_distribution', models.DateField(null=True)),
                ('role', models.ManyToManyField(null=True, to='gold_app.Role')),
                ('user_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gold_app.branch')),
                ('user_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gold_app.center')),
                ('user_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gold_app.group')),
            ],
        ),
        migrations.CreateModel(
            name='gold_lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=9)),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=9)),
                ('outstanding_amount', models.IntegerField()),
                ('jewller_name', models.CharField(max_length=50)),
                ('jewller_mobile', models.CharField(max_length=12)),
                ('jewller_address', models.CharField(max_length=128)),
                ('jewller_landmark', models.CharField(max_length=30)),
                ('jewller_working_hours', models.CharField(max_length=30)),
                ('jewller_holidays', models.CharField(max_length=30)),
                ('schedule_retrieval', models.DateField()),
                ('tr_created', models.DateField()),
                ('tr_gold_lot_received', models.DateField()),
                ('tr_handover_to_admin', models.DateField()),
                ('tr_cancellation', models.DateField()),
                ('gla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_app.gla')),
            ],
        ),
        migrations.CreateModel(
            name='community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=30)),
                ('comm_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_app.branch')),
            ],
        ),
        migrations.AddField(
            model_name='center',
            name='collection_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_app.collection_day'),
        ),
        migrations.AddField(
            model_name='center',
            name='collection_start_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_app.collection_time'),
        ),
    ]
