# Generated by Django 3.1.2 on 2020-11-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gla',
            name='calc_emi_1_year_gl',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='calc_emi_2_year_gl',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='calc_emi_3_year_gl',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='gl_cot_repayment',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='gl_gold_appraisal_fee',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='gl_gold_net_weight',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='gl_interest_rate',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='gl_loan_amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='gl_lpf',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='gl_share_purchase',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='gl_tenure',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='gl_total_retrieval_amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='param_base_share_value',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='param_cot_repay_rate_recommended',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='param_gold_appraisal_rate',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='param_gold_rate_gl',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='param_gold_rate_glg',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='param_gold_rate_glp',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='param_interest_rate_gl',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='param_interest_rate_glg',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='param_interest_rate_glp',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='param_lpf_rate',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='param_share_purchase_rate',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='reason_for_cancellation',
            field=models.TextField(blank=True, default='Cancel', null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='req_gold_loan_amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='req_max_loan_amount_gl',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='req_max_loan_amount_glg',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gla',
            name='req_max_loan_amount_glp',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
