# Generated by Django 3.1.2 on 2020-11-03 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gl_lead',
            name='date_of_lead',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='gla',
            name='borrower',
            field=models.ForeignKey(default='0000', on_delete=django.db.models.deletion.CASCADE, to='gold_app.user'),
        ),
        migrations.AlterField(
            model_name='gla',
            name='gla_application_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
