# Generated by Django 3.1.2 on 2020-10-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_registred',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_whatsapp',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
