# Generated by Django 3.1.2 on 2020-11-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0002_auto_20201103_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gl_lead',
            name='lead_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
