# Generated by Django 3.1.2 on 2020-10-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0002_auto_20201018_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='center_code',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
