# Generated by Django 3.1.2 on 2020-10-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0003_auto_20201018_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_code',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
