# Generated by Django 3.1.2 on 2020-11-07 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0004_auto_20201103_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='gla',
            name='gla_gl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gold_app.gl_lead'),
        ),
    ]
