# Generated by Django 3.1.2 on 2020-10-18 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0005_auto_20201018_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection_day',
            name='id',
        ),
        migrations.RemoveField(
            model_name='collection_time',
            name='id',
        ),
        migrations.AddField(
            model_name='collection_day',
            name='coll_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='collection_time',
            name='coll_time_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='center',
            name='center_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='collection_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gold_app.collection_day'),
        ),
        migrations.AlterField(
            model_name='center',
            name='collection_start_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gold_app.collection_time'),
        ),
        migrations.AlterField(
            model_name='collection_day',
            name='collection_day',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collection_time',
            name='collection_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='comm_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gold_app.branch'),
        ),
        migrations.AlterField(
            model_name='community',
            name='community_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
    ]
