# Generated by Django 3.1.2 on 2020-11-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0005_gla_gla_gl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gl_lead',
            old_name='enquiry',
            new_name='member',
        ),
    ]
