# Generated by Django 3.1.2 on 2020-10-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0006_auto_20201018_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection_time',
            name='collection_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
