# Generated by Django 3.1.2 on 2020-11-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0006_auto_20201108_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='gla',
            name='calc_emi_1_year_gl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gla',
            name='calc_emi_2_year_gl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gla',
            name='calc_emi_3_year_gl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gla',
            name='req_max_loan_amount_gl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gla',
            name='req_max_loan_amount_glg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gla',
            name='req_max_loan_amount_glp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gla',
            name='retrieval',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='null', max_length=20, null=True),
        ),
    ]
