# Generated by Django 3.1.2 on 2020-10-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0007_auto_20201018_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='center',
        ),
    ]
