# Generated by Django 3.1.2 on 2020-10-23 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0008_remove_group_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='gla',
            name='borrower',
            field=models.ForeignKey(default='mem_num', on_delete=django.db.models.deletion.CASCADE, to='gold_app.user'),
        ),
        migrations.AlterField(
            model_name='gla',
            name='gla_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_app.branch', to_field='branch_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mem_num',
            field=models.CharField(default='00000', max_length=100, primary_key=True, serialize=False),
        ),
    ]
