# Generated by Django 3.1.2 on 2020-10-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0009_auto_20201023_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gla',
            name='id',
        ),
        migrations.AddField(
            model_name='gla',
            name='gla_application_id',
            field=models.IntegerField(default='0', primary_key=True, serialize=False),
        ),
    ]
