# Generated by Django 3.1.2 on 2020-10-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0010_auto_20201024_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='gla',
            name='dummy',
            field=models.CharField(default='hello', max_length=30),
        ),
    ]
