# Generated by Django 3.1.2 on 2020-10-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0011_gla_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gla',
            name='gla_application_id',
            field=models.IntegerField(default='1', primary_key=True, serialize=False),
        ),
    ]
