# Generated by Django 3.1.2 on 2020-10-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0012_auto_20201027_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gla',
            name='dummy',
        ),
    ]
