# Generated by Django 3.1.2 on 2020-10-29 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0014_gla_dummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='GL_lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_status', models.CharField(max_length=40)),
                ('date_of_lead', models.DateField()),
                ('enquiry_id', models.ForeignKey(default='mem_num', on_delete=django.db.models.deletion.CASCADE, to='gold_app.user')),
                ('lead_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_app.branch', to_field='branch_name')),
            ],
        ),
    ]
