# Generated by Django 3.1.2 on 2020-10-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0015_gl_lead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gl_lead',
            old_name='enquiry_id',
            new_name='enquiry',
        ),
    ]
