# Generated by Django 3.1.2 on 2020-10-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0016_auto_20201029_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gl_lead',
            old_name='enquiry',
            new_name='member',
        ),
    ]
