# Generated by Django 3.1.2 on 2020-10-30 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0017_auto_20201031_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gl_lead',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold_app.user'),
        ),
    ]
