# Generated by Django 3.1.2 on 2020-10-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0018_auto_20201031_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gl_lead',
            name='date_of_lead',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gl_lead',
            name='lead_status',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
